# Generated by Django 4.2 on 2023-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'France')], default='en', help_text='Book language', max_length=2),
        ),
    ]
